defaults:
  - dataset: local
  - model: EABMIL
  - settings: config
  - _self_

hydra:
  job:
    chdir: true
    config:
      override_dirname:
        exclude_keys:
          - seed
  sweep:
    dir: multirun/${model.name}
    subdir: ${hydra.job.override_dirname},seed=${seed}

use_cuda: true
seed: 0
path: model_weights.pth