defaults:
  - dataset: config
  - model: EABMIL
  - settings: config
  - _self_

hydra:
  job:
    chdir: true
    config:
      override_dirname:
        exclude_keys:
          - seed
  sweep:
    dir: /gs/bs/tga-mdl/hayashi-mdl/NWPU-RESISC45-TEST
    subdir: ${model.name}

use_cuda: true
seed: 0
path: model_weights.pth